src/App.jsx, src/components/layout/Header.jsx, src/components/layout/Layout.jsx
=> FEAT: [추가] 헤더 레이아웃 구현

src/components/layout/Header.jsx
=> STYLE: [수정] 정렬 관련 css 수정

src/App.jsx, src/pages/Login.jsx
=> FEAT: [추가] 로그인 페이지 와이어 프레임 구현

package-lock.json, package.json, src/components/common/Tabbar.jsx, src/pages/Compare.jsx
=> FEAT: [추가] 탭 바 와이어프레임 구현

src/pages/Compare.jsx
=> STYLE: [개선] 그래프 색 개선

src/assets/img/pick.svg, src/components/common/Tabbar.jsx, src/pages/Detail.jsx
=> FEAT: [추가] 디테일 페이지 와이어프레임 구현

src/apis/apiInstance.jsx
baseURL만 설정된 instance를 추가하였습니다.
`REACT_APP_API_ENDPOINT`는 슬랙에 공유드린 .env파일 관련 메세지 확인 부탁드립니다.
=> FEAT: [추가] axios instance 파일 추가

src/pages/Login.jsx
=> FEAT: [추가] 일반 로그인 기능 구현

src/pages/Search.jsx
=> FEAT: [추가] react-query 이용하여 서버 데이터 적용

package-lock.json, package.json, src/pages/Login.jsx
=> FEAT: [추가] 로그인 기능 추가 구현

package-lock.json, package.json, src/components/common/CompareBox.jsx, src/index.jsx, src/pages/Search.jsx, src/recoil/recoilStore.js
=> DOCS: [개선] compareBox의 배열을 recoil로 분리

src/components/common/CompareBox.jsx, src/pages/Search.jsx, src/recoil/recoilStore.js
=> FEAT: [개선] recoil을 반영하여 비교함 개선

package-lock.json, package.json, src/App.jsx, src/apis/apiInstance.jsx, src/pages/User.jsx
=> FEAT: [추가] 마이페이지 업데이트

src/pages/User.jsx
=> FEAT: [추가] 프로필 이미지, 닉네임 수정기능 구현

src/pages/Compare.jsx, src/query/versusQuery.js
=> FEAT: [개선] 비교페이지 api 적용 및 그래프 변경, 디자인 개선

src/pages/Search.jsx
=> STYLE: [개선] 서치 페이지 디자인 뷰 변경

src/App.jsx, src/components/layout/Header.jsx, src/components/layout/Layout.jsx, src/pages/Login.jsx, src/pages/User.jsx
=> FEAT: [추가] 헤더 스타일,기능 추가 및 개선

src/components/layout/Header.jsx
=> FEAT: [추가] 헤더 메뉴 경로 설정

src/pages/User.jsx
=> FEAT: [개선] 이미지 수정 취소 기능 추가

src/components/common/CompareBox.jsx, src/components/common/Tabbar.jsx, src/components/layout/Header.jsx, src/pages/Compare.jsx
=> STYLE: [수정] 탭바 뷰 수정

src/components/common/CompareBox.jsx
=> STYLE: [개선] 이미지가 없을 경우 대체 이미지 반영

src/components/common/LikeItBtn.jsx, src/components/common/productList.jsx, src/pages/Compare.jsx, src/pages/Search.jsx, src/pages/User.jsx, src/query/likeQuery.js
=> FEAT: [추가] productList 공통 컴포넌트 생성

src/components/common/LikeItBtn.jsx, src/components/common/productList.jsx, src/pages/User.jsx, src/query/likeQuery.js
=> FEAT: [추가] 찜하기 api 적용

src/components/common/CompareBox.jsx, src/pages/Compare.jsx
=> FEAT: [추가] 범례에 마우스 오버 시 성분 설명 박스 구현

src/App.jsx, src/pages/User.jsx
=> FEAT: [추가] 마이페이지 회원탈퇴 기능 구현

src/pages/Compare.jsx
=> FEAT: [추가] 비로그인 상태로 비교 페이지 진입 시 메인페이지로 이동

src/pages/Compare.jsx, src/pages/User.jsx
=> FEAT: [개선] 마이페이지 찜 목록에 dibs 추가 입력하여 뷰 개선

src/components/common/productList.jsx
=> FEAT: [수정] productType이 배열로 바뀐 것 반영

src/pages/Compare.jsx
=> STYLE: [수정] 성분 설명 박스 뷰 수정 반영

src/App.jsx, src/pages/Login.jsx, src/pages/User.jsx
=> FEAT: [추가] 일반로그인, 소셜로그인 회원탈퇴 구현

src/pages/User.jsx
=> DOCS: [개선] 로그인 방식에 따른 회원탈퇴 기능 코드 수정

src/pages/Signup.jsx
=> STYLE: [개선] 회원가입 페이지 디자인 수정

src/components/layout/Header.jsx, src/pages/Signup.jsx
헤더 스크롤 시 화면 맨 위에 fix 되어 붙도록 수정 및 보더 수정 , 회원가입 페이지 백그라운드 사이즈 수정 #13
=> STYLE: [개선] 헤더, 회원가입 페이지 디자인 수정

src/pages/Compare.jsx, src/pages/main/Main.jsx
=> FEAT: [수정] 비교 페이지 디자인 반영

src/pages/Signup.jsx, src/query/signupQuery.js
=> FIX: [개선] 회원가입 페이지 가입 완료 후 로그인 페이지 이동 코드수정

src/pages/Signup.jsx, src/query/detailQuery.js
=> FIX: [개선] 상세페이지 찜기능 api 연결 수정

src/pages/Compare.jsx
=> STYLE: [개선] 비교 페이지 카드 수정

src/App.jsx, src/contents/FindId.jsx, src/pages/FindAccount.jsx, src/pages/Login.jsx
=> FEAT: [추가] 아이디, 비밀번호 찾기 페이지 뷰 구현 및 아이디 찾기 컴포넌트 구현

src/pages/Signup.jsx
전송된 인증번호가 없는 경우 인증번호 전송을 요청하는 상태 문구 추가 #13
=> FIX: [개선] 회원가입 페이지 인증 관련 코드 수정

src/pages/Compare.jsx
=> FEAT: [수정] 약 총 용량의 위치 및  디자인 변경 반영

src/contents/FindId.jsx
=> FEAT: [추가] 아이디 찾기 API 연결 구현

src/contents/FindId.jsx
=> STYLE: [추가] 아이디 찾기 후 유저 이미지 스타일 추가

src/pages/Login.jsx
=> STYLE: [삭제] input 커서 깜빡거림 없애는 코드 삭제

src/pages/User.jsx
=> DOCS: [개선] 프로필 이미지 수정 input 파일 확장자 제한

src/pages/User.jsx
=> FEAT: [추가] 회원탈퇴 전 알림창 추가

src/pages/User.jsx
=> FEAT: [추가] 프로필 사진 수정 시 이미지 업로드 용량 제한 구현

src/pages/User.jsx
=> FEAT: [개선] 이미지 파일 업로드 시 같은 파일도 다시 선택할 수 있도록 초기화 코드 구현

src/pages/User.jsx
=> STYLE: [개선] 꿀팁 박스 마우스 오버 시 블러 효과 수정

src/apis/apiInstance.jsx
`refreshToken` 기한 만료 시 에러 처리를 위해 구현했던 코드가 같은 `response.status` 에서 모두 반응하여 삭제, 재구현 예정
=> FIX: [삭제] 인터셉터 에러핸들링 부분 삭제

src/App.jsx, src/pages/User.jsx
=> STYLE: [개선] 회원탈퇴 모달 디자인 변경

src/components/layout/Header.jsx, src/pages/Search.jsx
=> FIX: [수정] toLocaleString 인식 오류 수정

src/App.jsx, src/components/common/Tabbar.jsx, src/contents/Reviews.jsx, src/pages/AddReviews.jsx, src/pages/Detail.jsx
=> FEAT: [추가] 리뷰 컴포넌트, 리뷰 작성 페이지 뷰 구현

src/contents/MaterialList.jsx, src/pages/AllergySearch.jsx
=> FEAT: [추가] 알러지 성분 등록 페이지 뷰, 일부 api 연결 구현

src/pages/AllergySearch.jsx
=> FEAT: [추가] 알러지 성분 검색 결과 페이지네이션 구현

src/contents/MaterialList.jsx
=> DOCS: [개선] 검색결과 추가 정보 없을 경우 뷰 수정

src/pages/SocialLogin.jsx
=> DOCS: [삭제] setSearchParams 코드 삭제

src/App.jsx, src/contents/Reviews.jsx, src/pages/AddReviews.jsx
=> FEAT: [추가] 리뷰 작성 페이지 디자인 추가, api 연결

src/contents/Allergy.jsx
=> DOCS: [개선] 알러지 성분 조회 결과 추가 정보 없을 경우 뷰 수정

src/App.jsx, src/contents/Reviews.jsx, src/pages/AddReviews.jsx
=> FEAT: [추가] 리뷰 컴포넌트, 리뷰 작성 페이지 기능 추가

src/pages/AllergySearch.jsx, src/pages/SocialLogin.jsx, src/pages/User.jsx
=> DOCS: [수정] 마이페이지 닉네임,탭바 디자인 일부 수정

package-lock.json, package.json, src/App.jsx, src/components/layout/ChatBox.jsx
=> FEAT: [추가] 챗봇 구현

src/components/layout/ChatBox.jsx
=> FEAT: [수정] 채팅방 입장 시 콘솔 뜨는 부분 삭제

src/components/layout/ChatBox.jsx
=> FIX: [수정] 10분에 채팅이 출력되면 분이 010으로 뜨는 현상 수정

src/components/layout/ChatBox.jsx
=> FIX: [수정] 마지막 글자가 한 번 더 출력되는 현상 수정

src/components/layout/ChatBox.jsx
=> FIX: [수정] 공백으로 채팅이 작성될 수 없게 수정

src/components/layout/ChatBox.jsx
=> FIX: [수정] 공백으로 채팅 입력 시 채팅 등록이 안되도록 변경

src/components/common/productList.jsx
=> STYLE: [수정] 디자인 수정 반영

src/components/common/productList.jsx, src/index.css, src/pages/Search.jsx
=> STYLE: [수정] 검색바 디자인 수정 반영

src/App.jsx, src/components/common/CompareBox.jsx, src/components/common/productList.jsx, src/pages/Compare.jsx, src/recoil/recoilStore.js
=> FEAT: [수정] 비교함에 2개 담는 때만 자동으로 오픈되도록 수정

src/pages/Detail.jsx
=> FIX: [수정] 디테일 페이지가 불러와지지 않는 현상 수정

src/components/layout/ChatBox.jsx, src/index.css
=> FEAT: [추가] 관리자 뷰 구현 및 작업

package-lock.json, package.json, src/App.jsx, src/components/common/CompareBox.jsx, src/pages/Compare.jsx, src/pages/Detail.jsx, src/pages/Laptop/LaptopCompare.jsx, src/pages/Laptop/LaptopDetail.jsx, src/pages/Search.jsx, src/pages/User.jsx, src/pages/main/FirstSection.jsx, src/pages/main/FourthSection.jsx, src/pages/main/SixthSection.jsx, src/pages/main/ThirdSection.jsx, src/query/useMediaQuery.js
=> FIX: [수정] 반응형 구현 중 충돌 문제 추가 수정

src/contents/MyReview.jsx
=> FEAT: [추가] 리뷰 '도움돼요','도움안돼요'구현 , 자세히보기 수정

src/contents/MyReview.jsx, src/pages/AddReviews.jsx
=> DOCS: [삭제] 사용하지 않는 코드 삭제

src/components/common/MiniNav.jsx
=> DOCS: [수정] 디테일, 경로 수정

src/components/layout/Header.jsx
=> FEAT: [추가] 토큰 오류 시 로그인 페이지로 이동

src/contents/Reviews.jsx
=> FEAT: [개선] 리뷰 컴포넌트 디테일 수정

src/components/common/MiniNav.jsx
=> STYLE: [개선] 네비게이션바 스타일 수정

src/contents/Reviews.jsx
=> FEAT: [추가] 검색순 드롭다운 기능 구현

src/App.jsx, src/contents/MyReview.jsx, src/pages/ModifyReviews.jsx
=> FEAT: [추가] '내가 쓴 리뷰' 수정 방식 변경, 리뷰 수정페이지 구현

src/contents/Reviews.jsx
=> FEAT: [추가] 상세페이지 리뷰 탭에서 내가 쓴 리뷰 수정기능 추가

src/pages/User.jsx
=> FEAT: [추가] response에 유저 이메일 추가되어 반영

src/components/layout/ChatBox.jsx
=> FEAT: [추가] 관리자와의 채팅 연결 구현

src/components/layout/ChatBox.jsx
=> FIX: [수정] 관리자한테 사용자가 보낸 메세지가 뜨지않던 현상 수정

src/pages/AllergySearch.jsx
=> STYLE: [추가] 알레르기 등록페이지 타이틀 추가

src/pages/AddReviews.jsx, src/pages/ModifyReviews.jsx
=> DOCS: [수정] textarea 글자 수 제한 문구 수정

src/contents/MyReview.jsx, src/contents/Reviews.jsx
=> STYLE: [개선] 숫자 입력 시 박스 밖으로 벗어나는 부분 수정

src/pages/Detail.jsx
=> FEAT: [추가] 상세페이지 마운트 시 스크롤 최상단 이동

src/pages/AllergySearch.jsx
=> FEAT: [추가] 재검색 시 상품 추가정보 접히도록 구현

src/components/common/CompareBox.jsx
=> FEAT: [수정] 비교함 카드 데이터 수정

src/components/common/CompareBox.jsx, src/components/layout/Header.jsx, src/contents/Allergy.jsx, src/contents/FindId.jsx, src/contents/FindPassword.jsx, src/contents/MaterialList.jsx, src/contents/MyLikeList.jsx, src/contents/MyReview.jsx, src/contents/Reviews.jsx, src/pages/AddReviews.jsx, src/pages/AllergySearch.jsx, src/pages/FindAccount.jsx, src/pages/Laptop/LaptopDetail.jsx, src/pages/ModifyReviews.jsx, src/pages/User.jsx
알러지 검색 및 등록, 리뷰, 탈퇴하기 반응형 적용 #161
=> FEAT: [추가] 반응형 추가 구현

src/pages/Search.jsx, src/recoil/recoilStore.js
=> FEAT: [수정] 검색어를 recoil로 분리

src/contents/MyReview.jsx
=> FEAT: [추가] '내가 쓴 리뷰' 조회 시에는 '도움 안돼요' 카운트도 확인 가능

src/components/layout/ChatBox.jsx
=> FEAT: [수정] 관리자 퇴장 이벤트 변경 반영

src/pages/main/FirstSection.jsx, src/pages/main/FourthSection.jsx
=> DOCS: [수정] 오타,줄바꿈 수정

src/components/layout/ChatBox.jsx
=> FIX: [수정] 챗봇 최소화하면 메세지가 사라지는 현상 수정

src/pages/Signup.jsx
=> FEAT: [추가] 휴대폰 번호 중복검사 api 적용

src/pages/Detail.jsx, src/pages/Laptop/LaptopDetail.jsx
=> STYLE: [수정] 디테일 페이지 스타일 수정

src/pages/main/SixthSection.jsx
=> FEAT: [추가] 마지막 섹션 버튼에 검색페이지로 링크 적용

src/components/layout/ChatBox.jsx
=> FEAT: [추가] 방 입장 시 기존 채팅 출력

src/pages/Login.jsx
=> FEAT: [추가] 토큰 있을 시 로그인 페이지 진입 막음

src/contents/Reviews.jsx
=> FEAT: [추가] 토큰 없을 경우 리뷰작성, 도움돼요, 도움안돼요 불가능하게 처리

src/contents/Reviews.jsx
=> DOCS: [추가] 신고하기 기능 구현 전 버튼에 alert 처리

src/pages/Compare.jsx, src/pages/Detail.jsx, src/pages/Laptop/LaptopCompare.jsx, src/pages/Laptop/LaptopDetail.jsx, src/pages/Signup.jsx
=> FIX : [수정] 비교페이지 알러지 성분 관련 UI 오류 주석처리

src/pages/Compare.jsx, src/pages/Laptop/LaptopCompare.jsx, src/pages/Laptop/LaptopDetail.jsx
=> FIX : [수정] 비교페이지 알러지 성분 관련 UI 오류 주석처리2

src/pages/Compare.jsx
=> FIX: [수정] 알러지 성분 그래프 색상 수정

src/pages/Laptop/LaptopCompare.jsx
=> FIX: [수정] 랩탑에서 비교하기 그래프 색상 수정

src/pages/Compare.jsx
=> FEAT: [수정] 비교 범례 넘칠 때만 스크롤이 나타나도록 수정

src/pages/Laptop/LaptopCompare.jsx
=> FIX: [수정] 랩탑 버전 그래프 범례 수정

src/components/common/Tabbar.jsx
=> STYLE: [수정] 탭바 선 위치 조정

src/pages/Search.jsx
=> STYLE: [수정] 서치 바 포커스 시 디자인 반영

src/contents/MypageTab.jsx
=> FIX: [수정] 마이페이지 탭바 디자인 디테일 수정

src/components/layout/Header.jsx
=> FIX: [수정] 헤더 버튼 디테일 수정

src/contents/MaterialList.jsx
=> FIX: [수정] 폰트 수정

src/components/layout/Header.jsx, src/contents/Reviews.jsx, src/pages/AllergySearch.jsx
=> FIX: [수정] 디자인 디테일 수정

src/pages/Search.jsx, src/query/searchQuery.js
=> FEAT: [추가] 검색 페이지 추천 검색어 추가

src/pages/Search.jsx
=> FIX: [수정] 서치페이지에 공백으로 검색버튼 클릭 시 오류 수정

src/contents/MyReview.jsx
=> FIX: [수정] '내가 쓴 리뷰' 디자인 디테일 수정

src/components/common/CompareBox.jsx
=> STYLE: [수정] 비교함 컴포넌트 디자인 수정 반영

src/pages/Compare.jsx, src/pages/Laptop/LaptopCompare.jsx
=> STYLE: [수정] 비교 페이지 디자인 변경 반영

src/pages/Search.jsx
=> STYLE: [수정] 서치 페이지 인기검색어 디자인 반영

src/pages/AllergySearch.jsx
=> FIX: [수정] 서치바 디테일 수정

src/components/common/CompareBox.jsx
=> FIX: [수정] 랩탑 버전에서의 비교함 위치 수정

src/components/layout/ChatBox.jsx
=> FEAT: [수정] 정해진 요일 및 시간에만 관리자 채팅 연결 활성화

src/App.jsx, src/apis/apiInstance.jsx, src/components/layout/Header.jsx, src/pages/Login.jsx, src/pages/SocialLogin.jsx, src/pages/User.jsx, src/query/userQuery.js, src/recoil/recoilStore.js
=> FEAT: [추가] 유저 관련 파트 리액트쿼리, 리코일 사용하여 리팩토링

src/components/common/CompareBox.jsx, src/recoil/recoilStore.js
=> FEAT: [수정] 새로고침해도 비교함이 초기화되지 않도록 수정

src/App.jsx, src/components/common/Spinner.jsx, src/pages/SocialLogin.jsx
=> FEAT: [개선] 소셜로그인 로딩화면 적용

src/App.jsx
=> FIX: [수정] 루트 수정

src/pages/Signup.jsx
=> FIX: [삭제] 회원가입 페이지 이메일 인증번호 관련 ui 삭제

src/components/common/CompareBox.jsx, src/components/common/productList.jsx, src/recoil/recoilStore.js
=> FIX: [수정] 비교함 모드 변경 방식 변경

src/components/common/Tabbar.jsx, src/pages/Detail.jsx, src/pages/Laptop/LaptopDetail.jsx
=> FEAT: [추가] 탭바 리뷰탭에 카운트 반영

src/pages/User.jsx
=> STYLE: [개선] 필너츠 꿀팁 마우스 오버 시 배경div 드래그 막기

src/pages/Compare.jsx, src/pages/Laptop/LaptopCompare.jsx
=> STYLE: [수정] 비교페이지 디자인 수정 반영

src/contents/Allergy.jsx, src/contents/MaterialList.jsx
=> FIX: [수정] 폰트 굵기 수정

src/contents/FindId.jsx, src/contents/FindPassword.jsx, src/pages/Signup.jsx
=> FEAT: [추가] 휴대폰 인증번호 전송 시 타이머 발동 기능 구현

src/pages/Compare.jsx, src/pages/Laptop/LaptopCompare.jsx
=> STYLE: [수정] 비교페이지 상품 카드 디자인 반영

src/components/common/productList.jsx
=> STYLE: [수정] 상품 리스트 카드 디자인 변경 반영

src/pages/Search.jsx
=> FIX: [수정] 서치 바 검색 완료 시 onBlur 처리

src/pages/Laptop/LaptopCompare.jsx
=> FIX: [수정] 토큰 없을때 비교하기 페이지 진입 시 로그인 페이지로 이동(laptop 해상도 일때 수정)

src/components/layout/ChatBox.jsx
=> FIX: [수정] 일정 시간 이외에도 관리자 채팅 버튼이 활성화되는 현상 수정

src/pages/Login.jsx
=> FEAT: [추가] 로그인 엔터키 핸들러 추가

src/components/common/Spinner.jsx
=> STYLE: [수정] 디테일 수정

src/contents/Reviews.jsx, src/pages/AddReviews.jsx, src/pages/ModifyReviews.jsx
=> REFACTOR: [개선] 중복되는 getProfile 함수 삭제, recoilState로 유저정보 적용

src/pages/Login.jsx, src/query/userQuery.js
=> REFACTOR: [개선] 로그인 api 리액트 쿼리 반영

src/contents/FindId.jsx, src/contents/FindPassword.jsx, src/pages/Signup.jsx
=> FIX: [개선] 이메일, 휴대폰 중복확인 작동안하는 오류 수정

src/contents/MyReview.jsx
=> FIX: [수정] 디테일 수정

package-lock.json, package.json, src/pages/Search.jsx
=> FIX: [수정] 서치페이지 맥 한글 엔터오류 반영

src/pages/Detail.jsx, src/pages/Laptop/LaptopDetail.jsx
=> STYLE: [개선] 그래프 성분 툴팁이 총용량 더보기에 가려지는 문제 수정

src/contents/FindPassword.jsx, src/pages/Signup.jsx
=> FIX: [개선] alert 대체 모달 적용

package-lock.json, package.json, src/contents/FindId.jsx, src/contents/FindPassword.jsx, src/pages/Signup.jsx
=> FIX: [개선] 회원가입, 이메일,비번 찾기 onChange 이벤트에 debounce 함수 추가

src/contents/MyReview.jsx, src/contents/Reviews.jsx
=> FIX: [수정] 리뷰 조회 api 정렬 관련 수정됨에 따라 프로퍼티 수정

src/pages/AllergySearch.jsx
=> DOCS: [개선] 알레르기 성분 검색바 하단 가이드 변경

src/pages/AllergySearch.jsx
=> DOCS: [수정] 문구 수정

src/contents/MyReview.jsx, src/contents/Reviews.jsx
=> FIX: [수정] 리뷰 작성일자 한국 시간으로 변경

src/components/layout/ChatBox.jsx, src/components/layout/Footer.jsx, src/pages/AllergySearch.jsx
=> FIX: [수정] 채팅박스가 검색바에 가려지는 현상 수정

src/pages/Signup.jsx
certification boolean 값 추가 요청 #13
=> [FEAT]: 회원가입 post api req 추가

src/contents/FindId.jsx, src/contents/FindPassword.jsx, src/pages/Signup.jsx
=> FIX: [개선] 이메일, 휴대폰 번호 onChange 이벤트에 debounce 함수 제거
